import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const josfin = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "D4 Community",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <body className={`${josfin.className} antialiased`}>{children}</body>
      </ThemeProvider>
      </html>
  );
}
